version: '3'

services:
  twitterBack:
    image: webdevops/php-apache:8.0
    container_name: twitterBack
    ports:
      - "8080:80"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
      - WEB_DOCUMENT_INDEX=index.php
    expose:
      - 80
    volumes:
      - ./twitterBack:/var/www
      - tmp:/tmp
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
  tmp:
